### ISSUE TITLE
Minigalaxy crashes on startup due to unsuppoted locale

### ISSUE THREAD

**Issue by DirtyJukebox** [flathub/io.github.sharkwouter.Minigalaxy#2]
Title says it all, but for completeness, Minigalaxy crashes on start if the user has a non `en_US.UTF` or `C` as the `LANG` environment variable.

**Stack trace**
```
khalil:~ % flatpak run io.github.sharkwouter.Minigalaxy

(minigalaxy:2): Gtk-WARNING **: 20:12:59.150: Locale not supported by C library.
        Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/app/bin/minigalaxy", line 66, in <module>
    main()
  File "/app/bin/minigalaxy", line 57, in main
    from minigalaxy.ui import Window
  File "/app/lib/python3.7/site-packages/minigalaxy/ui/__init__.py", line 2, in <module>
    from minigalaxy.ui.window import Window
  File "/app/lib/python3.7/site-packages/minigalaxy/ui/window.py", line 5, in <module>
    from minigalaxy.ui.login import Login
  File "/app/lib/python3.7/site-packages/minigalaxy/ui/login.py", line 8, in <module>
    from minigalaxy.translation import _
  File "/app/lib/python3.7/site-packages/minigalaxy/translation.py", line 7, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
**Workaround**
```
flatpak --user override --env=LANG=C
```
I'm not sure if this is a flatpak packaging bug (like Discord crashing when the timezone is different), or an upstream (the non-flatpak Minigalaxy) one, if this is the wrong place to report this just say it =p

Fell free to ask any further logs/questions if needed.

**Comment by tim77** [comment]
Bloody bug https://github.com/flathub/net.lutris.Lutris/issues/78 Thanks for reporting.

**Comment by hfiguiere** [comment]
You could just add `--env=LANG=C` in the manifest.
